### ISSUE TITLE
API exposed through monkey patching?

### ISSUE THREAD

**Issue by nkochakian** [kensnyder/any-date-parser#1]
Is there any reason why some of the parsing functions are exposed through Date instead of the exported Parser instance? It seems like an odd design decision.

**Comment by kensnyder** [comment]
Thanks for the observation.

The parser exposes parsing strings from both `parser.fromString()` and `Date.fromString()`; and exposes parsing other things from both `parser.fromAny()` and `Date.fromAny()`.

I'll add that to the README.md as a second usage example.

**Comment by kensnyder** [comment]
These have been clarified in the README.
