### ISSUE TITLE
fromString() bug

### ISSUE THREAD

**Issue by kolmakova** [kensnyder/any-date-parser#12]
Hi! I'm using this lib in my project with the timeline. I've noticed today that some dates are not parsing via fromString, and a couple of days ago, everything was ok:

<img width="879" alt="Screenshot 2022-01-31 at 17 15 28" src="https://user-images.githubusercontent.com/6749981/151792398-88a4ba62-ac4e-419a-b270-a7df6f7a8f31.png">

I've done some research, found a problem in `/src/fromString/fromString.js` in this piece of code:

```js
const date = new Date();
// default to current year, month and day
if (typeof parsed.year === 'number') {
    date.setUTCFullYear(parsed.year);
}
if (typeof parsed.month === 'number') {
    date.setUTCMonth(parsed.month - 1);
}
if (typeof parsed.day === 'number') {
    date.setUTCDate(parsed.day);
}
```

Today is 31st January and this code is trying to set 31st February while checking the current month. 31st February does not exist, as well as, 31st Apr, 31st Jun, 31st Sep, and 31st Nov, so this results in inconsistency. According to the [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setUTCDate#description) for `setUTCDate()`, this thing happens if you'll try to set the 31st day for a month that does not has it:

> If a parameter you specify is outside of the expected range, setUTCDate() attempts to update the date information in the Date object accordingly. For example, if you use 40 for dayValue, and the month stored in the Date object is June, the day will be changed to 10 and the month will be incremented to July.

All my data in Feb, Apr, Jun, Sep have become a month older. I guess this relates to the leap year too.

**Comment by kensnyder** [comment]
@kolmakova, thank you for finding this problem. Do you think the solution is to use `setFullYear`, `setMonth` and `setDate`?

**Comment by kensnyder** [comment]
@kolmakova, can you provide the string you are running `fromString` on? The following test passes for me right now:

```js
const parser = require('../../../index.js');
describe('year month day', () => {
	it('should handle months with 31 days (GitHub issue #3)', () => {
		const actual = parser.fromString('2022-01-31');
		const expected = new Date(2022, 0, 31);
		expect(actual).toEqual(expected);
	});
});
```

Maybe it will fail later today when UTC rolls into Feb 1?

**Comment by kensnyder** [comment]
OK. Makes sense. I will try to publish a fix today.

**Comment by kensnyder** [comment]
Master branch is updated and npm is published.
