### ISSUE TITLE
Error parsing formatted dates

### ISSUE THREAD

**Issue by juanluispaz** [kensnyder/any-date-parser#2]
Hello,

Amazing library!!! :D

I'm trying to parse dates generated by the Intl format date in some locales, but I got an error indicating it is unable to parse the date.

Example:

```js
var d = new Date();
Date.fromString(d.toLocaleDateString('ar-EG'), 'ar-EG'); // Error
Date.fromString(d.toLocaleString('ko'), 'ko'); // Error
```

I extended the test to try with 210 locales and I got 90 errors:

```js

var locales = 'af-ZA am-ET ar-AE ar-BH ar-DZ ar-EG ar-IQ ar-JO ar-KW ar-LB ar-LY ar-MA arn-CL ar-OM ar-QA ar-SA ar-SY ar-TN ar-YE as-IN az-Cyrl-AZ az-Latn-AZ ba-RU be-BY bg-BG bn-BD bn-IN bo-CN br-FR bs-Cyrl-BA bs-Latn-BA ca-ES co-FR cs-CZ cy-GB da-DK de-AT de-CH de-DE de-LI de-LU dsb-DE dv-MV el-GR en-029 en-AU en-BZ en-CA en-GB en-IE en-IN en-JM en-MY en-NZ en-PH en-SG en-TT en-US en-ZA en-ZW es-AR es-BO es-CL es-CO es-CR es-DO es-EC es-ES es-GT es-HN es-MX es-NI es-PA es-PE es-PR es-PY es-SV es-US es-UY es-VE et-EE eu-ES fa-IR fi-FI fil-PH fo-FO fr-BE fr-CA fr-CH fr-FR fr-LU fr-MC fy-NL ga-IE gd-GB gl-ES gsw-FR gu-IN ha-Latn-NG he-IL hi-IN hr-BA hr-HR hsb-DE hu-HU hy-AM id-ID ig-NG ii-CN is-IS it-CH it-IT iu-Cans-CA iu-Latn-CA ja-JP ka-GE kk-KZ kl-GL km-KH kn-IN kok-IN ko-KR ky-KG lb-LU lo-LA lt-LT lv-LV mi-NZ mk-MK ml-IN mn-MN mn-Mong-CN moh-CA mr-IN ms-BN ms-MY mt-MT nb-NO ne-NP nl-BE nl-NL nn-NO nso-ZA oc-FR or-IN pa-IN pl-PL prs-AF ps-AF pt-BR pt-PT qut-GT quz-BO quz-EC quz-PE rm-CH ro-RO ru-RU rw-RW sah-RU sa-IN se-FI se-NO se-SE si-LK sk-SK sl-SI sma-NO sma-SE smj-NO smj-SE smn-FI sms-FI sq-AL sr-Cyrl-BA sr-Cyrl-CS sr-Cyrl-ME sr-Cyrl-RS sr-Latn-BA sr-Latn-CS sr-Latn-ME sr-Latn-RS sv-FI sv-SE sw-KE syr-SY ta-IN te-IN tg-Cyrl-TJ th-TH tk-TM tn-ZA tr-TR tt-RU tzm-Latn-DZ ug-CN uk-UA ur-PK uz-Cyrl-UZ uz-Latn-UZ vi-VN wo-SN xh-ZA yo-NG zh-CN zh-HK zh-MO zh-SG zh-TW zu-ZA'.split(' ');

var d = new Date();
var parsed = {};
var unsupported = [];
locales.forEach((locale) => {
    var p = Date.fromString(d.toLocaleString(locale), locale);
    parsed[locale] = p;
    if (p.invalid) {
        unsupported.push(locale);
    }
})

console.log(unsupported);
```

The following locales failed:

`
ar-AE ar-BH ar-DZ ar-EG ar-IQ ar-JO ar-KW ar-LB ar-LY ar-MA ar-OM ar-QA ar-SA ar-SY ar-TN ar-YE bg-BG bs-Cyrl-BA ca-ES da-DK de-AT de-CH de-DE de-LI de-LU el-GR en-029 en-AU en-BZ en-CA en-GB en-IE en-IN en-JM en-MY en-NZ en-PH en-SG en-TT en-US en-ZA en-ZW es-CO fa-IR fi-FI fil-PH fr-BE fr-CA fr-CH fr-FR fr-LU fr-MC he-IL hi-IN hr-BA hr-HR hu-HU id-ID it-CH it-IT ja-JP ko-KR lv-LV mr-IN ms-BN ms-MY nb-NO pl-PL pt-PT ro-RO ru-RU sk-SK sl-SI sr-Cyrl-BA sr-Cyrl-CS sr-Cyrl-ME sr-Cyrl-RS sr-Latn-BA sr-Latn-CS sr-Latn-ME sr-Latn-RS sv-FI ta-IN uk-UA vi-VN zh-CN zh-HK zh-MO zh-SG zh-TW
`

I only tested with `Date.toLocaleString` but there is as well `Date.toLocaleDateString` and `Date.toLocaleTimeString`

I made the test using Chrome 87.0.4280.88 (Build oficial) (x86_64) on macOS Big Sur 11.0.1 (20B29) importing the package from `https://cdn.jsdelivr.net/npm/any-date-parser@1.3.0/dist/browser-bundle.js`

Additionally, when I executed the function `Date.fromString` I expected to throw an error when failed, but instead, I got an object; this behaviour is not documented in the readme.

I hope this help to improve your amazing library.

Thanks!

**Comment by kensnyder** [comment]
Thanks for the report. Sorry for the delay.

I actually logged `d.toLocaleString(locale)` and saw the result is almost always in the format `4/19/2021, 10:04:02 AM`. I can remedy the problem by ignoring more symbol and space characters like the comma in that example.

`toLocaleString()` also takes a second parameter like `new Intl.DateTimeFormat()` does. [See MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat). It allows passing `dateStyle` and `timeStyle`.

Example:

```js
new Intl.DateTimeFormat('pl-PL', { dateStyle: 'full', timeStyle: 'long' }).format(new Date());
```

This approached has identified a lot of other formats this library could support. Probably with some minor tweaks. It's hard to say exactly how often these date formats appear in the real world. For example, I don't often see humans add commas between date and time like this: `4/19/2021, 10:04:02 AM`.

I'll put some work in and report back.

**Comment by kensnyder** [comment]
Dates like `4/19/2021, 10:04:02 AM` are now supported in v1.4.1, but only for `en-US` and other locales that actually use the month/day/year format according to [this Wikipedia table](https://en.wikipedia.org/wiki/Date_format_by_country).

**Comment by juanluispaz** [comment]
Parce a formated date open the door to use your library in complex situations like building date and time pickers; in this context handling the language is a horrible headache. I think your library is the first one that relays on Intl for that purpose without external language files.

I reran the test on the same conditions with the latest version of your library (1.4.5), and I found a big improvement, but still some failures (53):

`ar-AE ar-BH ar-DZ ar-EG ar-IQ ar-JO ar-KW ar-LB ar-LY ar-MA ar-OM ar-QA ar-SA ar-SY ar-TN ar-YE bg-BG bs-Cyrl-BA da-DK en-029 en-ZA es-PA es-PR fa-IR fi-FI fil-PH fr-CA hr-BA hr-HR hu-HU id-ID ja-JP ko-KR lv-LV nl-NL prs-AF sl-SI sr-Cyrl-BA sr-Cyrl-CS sr-Cyrl-ME sr-Cyrl-RS sr-Latn-BA sr-Latn-CS sr-Latn-ME sr-Latn-RS sv-FI ta-IN vi-VN zh-CN zh-HK zh-MO zh-SG zh-TW`

Amazing work!

**Comment by juanluispaz** [comment]
The bug #9 is one of the locales included in the list that is not working `nl-NL`

**Comment by juanluispaz** [comment]
I reran the test on the same conditions with the latest version of your library (1.5.1), and I found an improvement, `nl-NL` is not in the list anymore, but still some failures (52):

`ar-AE ar-BH ar-DZ ar-EG ar-IQ ar-JO ar-KW ar-LB ar-LY ar-MA ar-OM ar-QA ar-SA ar-SY ar-TN ar-YE bg-BG bs-Cyrl-BA da-DK en-029 en-ZA es-PA es-PR fa-IR fi-FI fil-PH fr-CA hr-BA hr-HR hu-HU id-ID ja-JP ko-KR lv-LV prs-AF sl-SI sr-Cyrl-BA sr-Cyrl-CS sr-Cyrl-ME sr-Cyrl-RS sr-Latn-BA sr-Latn-CS sr-Latn-ME sr-Latn-RS sv-FI ta-IN vi-VN zh-CN zh-HK zh-MO zh-SG zh-TW`

Amazing work!

**Comment by juanluispaz** [comment]
If I detail the failing formats, they are:

```js
{
    "٢٢‏/٩‏/٢٠٢١, ٩:٠٥:٤٣ م": "ar-AE, ar-BH, ar-EG, ar-IQ, ar-JO, ar-KW, ar-LB, ar-OM, ar-QA, ar-SY, ar-YE",
    "22‏/9‏/2021, 9:05:43 م": "ar-DZ, ar-LY, ar-TN",
    "22‏/9‏/2021, 21:05:43": "ar-MA",
    "١٥‏/٢‏/١٤٤٣ هـ في ٩:٠٥:٤٣ م": "ar-SA",
    "22.09.2021 г., 21:05:43 ч.": "bg-BG",
    "22.09.2021. 21:05:43": "bs-Cyrl-BA",
    "22.9.2021 21.05.43": "da-DK",
    "9/22/2021, 9:05:43 PM": "en-029, fil-PH",
    "2021/09/22, 21:05:43": "en-ZA",
    "09/22/2021 9:05:43 p. m.": "es-PA, es-PR",
    "۱۴۰۰/۶/۳۱،‏ ۲۱:۰۵:۴۳": "fa-IR, prs-AF",
    "22.9.2021 klo 21.05.43": "fi-FI",
    "2021-09-22, 21 h 05 min 43 s": "fr-CA",
    "22. 09. 2021. 21:05:43": "hr-BA, hr-HR",
    "2021. 09. 22. 21:05:43": "hu-HU",
    "22/9/2021 21.05.43": "id-ID",
    "2021/9/22 21:05:43": "ja-JP",
    "2021. 9. 22. 오후 9:05:43": "ko-KR",
    "2021.09.22. 21:05:43": "lv-LV",
    "22. 9. 2021 21:05:43": "sl-SI",
    "22.9.2021. 21:05:43": "sr-Cyrl-BA, sr-Cyrl-CS, sr-Cyrl-ME, sr-Cyrl-RS, sr-Latn-BA, sr-Latn-CS, sr-Latn-ME, sr-Latn-RS",
    "2021-09-22 21.05.43": "sv-FI",
    "22/9/2021, பிற்பகல் 9:05:43": "ta-IN",
    "21:05:43, 22/9/2021": "vi-VN",
    "2021/9/22 下午9:05:43": "zh-CN, zh-TW",
    "22/9/2021 下午9:05:43": "zh-HK, zh-MO",
    "2021年9月22日 下午9:05:43": "zh-SG"
}
```
