### ISSUE TITLE
Change timezone?

### ISSUE THREAD

**Issue by zisra** [kensnyder/any-date-parser#23]
How do I use parser.fromString assuming that the input is from a specific timezone?

**Comment by kensnyder** [comment]
@zisra You can append the timezone offset and it should get parsed. For example:

```js
const input = '2020-10-06T17:41:28';
Date.fromString(input + '-04:00');
```

**Comment by zisra** [comment]
@kensnyder How do I find out the default timezone?

**Comment by kensnyder** [comment]
@zisra On browser or node, you can get the timezone offset in minutes:

```js
const offsetMinutes = new Date().getTimezoneOffset();
```

If you need the timezone name for some reason, it depends a bit on the runtime and user locale.

```js
// timezone name will come at the end of the string:
import { defaultLocale } from 'any-date-parser';
new Intl.DateTimeFormat(defaultLocale, { timeZoneName: 'long' }).format(new Date());

// timezone name is USUALLY in parens at the end of the string:
new Date().toString();
```
