### ISSUE TITLE
Incorrect default language value

### ISSUE THREAD

**Issue by MrZillaGold** [kensnyder/any-date-parser#3]
When running the library on linux, the [`defaultLocale.js`](https://github.com/kensnyder/any-date-parser/blob/master/src/data/defaultLocale.js) module returns an invalid language tag: `en_us.utf-8`.

https://github.com/kensnyder/any-date-parser/blob/1406c5f747d6f8ed60cd0466557424e2f6453d24/src/Parser/Parser.js#L56

https://travis-ci.com/github/MrZillaGold/NameMCWrapper/jobs/501048262#L320

**Comment by kensnyder** [comment]
Fixed with version [1.4.2](https://github.com/kensnyder/any-date-parser/commit/5ad38fa82384fe909c562e3b0d5365df28f549f9).
