### ISSUE TITLE
import in typescript

### ISSUE THREAD

**Issue by gustawdaniel** [kensnyder/any-date-parser#4]
In webstorm I have error:

```
TS7016: Could not find a declaration file for module 'any-date-parser'. '/media/nvme/pro/cm/poc_fb_date_parse/node_modules/any-date-parser/index.js' implicitly has an 'any' type.   Try `npm i --save-dev @types/any-date-parser` if it exists or add a new declaration (.d.ts) file containing `declare module 'any-date-parser';`
```

To fix add option

```
"noImplicitAny": false
```

to `tsconfig.json`. Option explaination

> /* Raise error on expressions and declarations with an implied 'any' type. */

Source:

https://stackoverflow.com/a/62681335/6398044

I propose to describe it in docs.

**Comment by gustawdaniel** [comment]
There was other problem with import:

> Cannot use import statement outside a module

https://github.com/mochajs/mocha/issues/4531

Better fix:

replace `import from` by `require`.

```
const parser = require('any-date-parser')
```

**Comment by kensnyder** [comment]
@gustawdaniel I'm not so familiar with Typescript but I'm working on generating an index.d.ts file for this repo so that using it with Typescript is painless.

**Comment by kensnyder** [comment]
@gustawdaniel Version 1.4.5 now includes an `index.d.ts` file. Please let me know if there are any problems.

**Comment by WindBridges** [comment]
Hi. In my case, the package worked only if I use require: `const DateParser = require('any-date-parser')`. After I switched the project to `'type':'module'`, I can no longer use require, and `import DateParser from 'any-date-parser'` gives me a constant error: `Error:(4, 24) TS2306: File '.../node_modules/any-date-parser/index.d.ts' is not a module.` Can anyone advise any solution?

**Comment by WindBridges** [comment]
As a temporary solution, I added the line `declare module 'any-date-parser'` to the `types.d.ts` file in the root of my project. After that the error is gone, but of course there is no typing either.
