### ISSUE TITLE
What is the purpose of the locale parameter?

### ISSUE THREAD

**Issue by reactedlau** [kensnyder/any-date-parser#8]
Either I've found a bug or I am confused about the purpose of the `locale` parameter that many of the API's functions take. Let's say our date is May 10, 2021. In the US, this is written as `5/10/2021`. In France (locale `FR`), the convention is to write `10/05/2021`. For example:

```
new Intl.DateTimeFormat('FR').format(new Date('2021-05-10'))
> "10/05/2021"
```

But when I try to parse, I get:

```
parser.attempt('10/05/2021', 'FR')
> { month: 10, day: 5, year: 2021 }
```

It's interpreting the `10` as the month, like it's the US format, not as the day. 

Note that if I try an unambiguous date like May 19, 2021 (19/05/2021 in FR), it parses that correctly.

Expected Behavior
I would expect that `attempt()` uses the locale to decide whether a field is a date or month per that locale's conventions.

**Comment by kensnyder** [comment]
Hi @reactedlau. The `Intl` built-in does not include date parsing. It only includes date formatting. 

Passing a locale to the parser basically allows recognizing month names and other digit systems. Dates that are made entirely from traditional digits and symbols don't gain anything from knowing the locale.

One date format that is particularly troublesome to developers in general is differentiating M/D/Y from D/M/Y. I think the US is the only locale that uses M/D/Y.

Currently, the only way to disabled the M/D/Y parsing is to remove it:

```js
const parser = require('any-date-parser');
const monthDayYear = require('any-date-parser/src/formats/monthDayYear/monthDayYear.js');

parser.removeFormat(monthDayYear);
```

I could imagine a small change that would disable this rule if locale is anything other than `en-US`. Does that sound reasonable?

**Comment by kensnyder** [comment]
I had some time today, and went ahead and added the rule. A little research showed there are several other locales that use month day year and you can see the code change and list [here](https://github.com/kensnyder/any-date-parser/commit/9e06088dbfd8053729b676e9b8f72de90110e327#diff-26b367566ac80c829411ec557b6c3960e0ea378e05f3e90c8ed70bcb4ceecfd0).

Closing this issue because it now behaves how are expecting.

**Comment by reactedlau** [comment]
> I had some time today, and went ahead and added the rule. A little research showed there are several other locales that use month day year and you can see the code change and list [here](https://github.com/kensnyder/any-date-parser/commit/9e06088dbfd8053729b676e9b8f72de90110e327#diff-26b367566ac80c829411ec557b6c3960e0ea378e05f3e90c8ed70bcb4ceecfd0).
> 
> Closing this issue because it now behaves how are expecting.

Thanks, @kensnyder! After doing some research myself, I was just about to link you to the Wikipedia article that you referenced. I was pleasantly surprised to see that you've already resolved the issue!
