### ISSUE TITLE
Date parsing for Dutch (locale = `nl`) doesn't work

### ISSUE THREAD

**Issue by reactedlau** [kensnyder/any-date-parser#9]
I'm attempting to parse a date that was formatted by Intl.DateTimeFormat for the Netherlands. I'm getting “invalid date format”.

Example:
```
const formatter = Intl.DateTimeFormat(['nl'], { dateStyle: 'short'});
formatter.format(new Date());
> "02-06-2021"

var anyDateParser = require("any-date-parser")
anyDateParser.attempt("02-06-2021", 'nl')
> Object {invalid: "Unable to parse 02-06-2021"}
```

Running any-date-parser 1.4.5.

It seems to be the `-` that's tripping it up. As a workaround, would a global search/replace from `-` to `/` in the test string work? I can do that until there's a fix, but just want to make sure that I'm not introducing bugs in other locales.

Also, I tried the same for South Korea (`ko`) and saw the same problem. (I.e., the output from Intl.DateTimeFormat was not understood by any-date-parser.)

**Comment by kensnyder** [comment]
This issue is fixed in v1.5.1. Please note that the following locales interpret 02-06-2021 as 6 Feb 2021:

```js
// from monthDayYear.js
// see https://en.wikipedia.org/wiki/Date_format_by_country
// see https://www.localeplanet.com/icu/
locales: [
	'ee-TG', // Togo (Ewe)
	'en-AS', // American Samoa
	'en-CA', // Canada
	'en-FM', // Federated States of Micronesia
	'en-GH', // Ghana
	'en-GU', // Guam
	'en-KE', // Kenya
	'en-KY', // Cayman Islands
	'en-MH', // Marshall Islands
	'en-MP', // Northern Mariana Islands
	'en-US', // United States
	'en-VI', // US Virgin Islands
	'en-WS', // Western Samoa
	'sm-AS', // American Samoa (Samoan)
	'sm-SM', // Samoa
],
```
